### ISSUE TITLE
Extend to cloudpathlib 0.16.0

### ISSUE THREAD

**Issue by BLKSerene** [explosion/weasel#67]
Hi, `cloudpathlib 0.16.0` has been released, could you please update the requirement pin? And it seems that support for Python 3.12 is also fixed in the new version.

**Comment by adrianeboyd** [comment]
Thanks for the note, this should be updated in Weasel v0.3.3.

**Comment by ringohoffman** [comment]
@adrianeboyd would you consider removing the upper bound on `cloudpathlib` or making it `<1.0.0`? I have the same request for `0.17.0` and I imagine this will keep happening

**Comment by svlandeg** [comment]
Hi! No need to ping specific maintainers, but in the future it's probably better to open a new issue rather than comment on a closed ones. Anyway - I reopened this as I can see how this gets annoying. I assume we originally had the pin so strict because we worried about breaking minor versions. If that's not the case, we can go ahead and bump the upper pin (cf #78)

**Comment by ringohoffman** [comment]
@svlandeg https://github.com/explosion/weasel/pull/77
